name: Release CI

on: [push, pull_request]

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release
        run: |
          git tag -f nightly
          git push -f origin nightly
          gh release delete nightly -y || :
          gh release create nightly -t 'Nightly builds' -F CHANGELOG.md -p
        env:
          GH_TOKEN: ${{ github.token }}

  create_archive:
    name: Create chrome-shortcuts-nightly.zip
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install packages
        run: sudo snap install inkscape

      - name: Build release
        run: make release name=chrome-shortcuts version=nightly

      - name: Upload artifact
        run: gh release upload nightly releases/chrome-shortcuts-nightly.zip
        env:
          GH_TOKEN: ${{ github.token }}
